[package]
name = "git-loom"
version = "0.6.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
cliclack = "0.3"
colored = "3"
git2 = "0.20"
shell-escape = "0.1"
tempfile = "3"

[dev-dependencies]
